# Generated by Django 5.1 on 2024-08-31 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto'),
        ),
    ]
