# Generated by Django 5.1 on 2024-08-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stock_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_ammnt',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='description',
        ),
        migrations.AddField(
            model_name='producto',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
